name: Lint


on:
  workflow_call:
    inputs:
      GO_VERSION:
        type: string
        required: true

jobs:
  test:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3